builds:
  - main: cmd/mqlux/mqlux.go
    binary: mqlux
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
      - arm
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: 386
